### ISSUE TITLE
Errors when running python detect.py

### ISSUE THREAD

**Issue by kvv2018** [Fermes/yolov3-mxnet#2]
I get the following error when I run detect.py
Traceback (most recent call last):
  File "detect.py", line 246, in <module>
    prediction = write_results(prediction, num_classes, confidence=confidence, nms_conf=nms_thresh)
  File "/media/caffe-pc/TranscendSSD/yolov3-mxnet/yolov3-mxnet/utils.py", line 171, in write_results
    ious = bbox_iou(box1, box2, transform=False).asnumpy()
  File "/media/caffe-pc/TranscendSSD/yolov3-mxnet/yolov3-mxnet/utils.py", line 29, in bbox_iou
    box1 = nd.abs(box1)
  File "<string>", line 36, in abs
AssertionError: Argument data must have NDArray type, but got [[  87.90929413  116.13845062  307.02111816  289.9173584     0.9935807
     0.99926466    1.        ]
 [  87.90929413  116.13845062  307.02111816  289.9173584     0.9935807
     0.99926466    1.        ]
 [  87.90929413  116.13845062  307.02111816  289.9173584     0.9935807
     0.99926466    1.        ]]

Any ideas ?

**Comment by Fermes** [comment]
It has been fixed. I push the wrong version py file. So sorry for that.

**Comment by kvv2018** [comment]
Thanks
